apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: embulk-template
spec:
  templates:
    - name: embulk
      container:
        image: embulk:latest
        args: ['run', '/input/config.yml.liquid', '-r', '/output/resume-state.yml']
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
        volumeMounts:
        - name: output
          mountPath: /output
      volumes:
        - name: output
          emptyDir: {}
      inputs:
        artifacts:
        - name: embulk-config
          path: /input/config.yml.liquid
      outputs:
        parameters:
        - name: resume-state
          valueFrom:
            path: /output/resume-state.yml