apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: csv-to-stdout-sample
spec:
  entrypoint: embulk
  serviceAccountName: argo-workflow
  arguments:
    artifacts:
    - name: embulk-config
      raw:
        data: |
          in:
            type: file
            path_prefix: ../data/csv/
            parser:
              charset: UTF-8
              newline: CRLF
              type: csv
              delimiter: ','
              quote: '"'
              escape: '"'
              null_string: 'NULL'
              skip_header_lines: 1
              columns:
              - {name: customer_id, type: string}
              - {name: customer_name, type: string}
          out: 
            type: stdout       
  workflowTemplateRef:
    name: embulk-template