apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: embulk-template
spec:
  entrypoint: embulk
  templates:
    - name: embulk
      inputs:
        artifacts:
        - name: embulk-config
          path: /input/config.yml
      container:
        image: embulk:v0.1
        command: [java]
        args:  ["-jar", "/root/.embulk/bin/embulk", "run", "/input/config.yml"]
        volumeMounts:
        - name: credentials-volume
          mountPath: "/run/secrets/gcp-secret"
          readOnly: true
          subpath: gcp-secret
        resources:
          limits:
            memory: "4Gi"
            cpu: "2"
      volumes:
        - name: credentials-volume
          secret:
            secretName: volume-secret
            items:
            - key: gcp-secret
              path: gcp-secret