apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: slack
spec:
  templates:
  - name: failed-notification-to-slack
    volumes:
    - name: credentials-volume
      secret:
        secretName: credentials-volume
    container:
      image: curlimages/curl
      command: [sh, -c]
      args: [
        "curl -X POST --data-urlencode 'payload={
          \"text\": \"{{workflow.name}} finished\",
          \"blocks\": [
            {
              \"type\": \"section\",
              \"text\": {
                \"type\": \"mrkdwn\",
                \"text\": \"Workflow {{workflow.name}} {{workflow.status}}\",
              }
            }
          ]
        }'
        $WEBHOOKURL"
      ]
      env:
      - name: WEBHOOKURL
        valueFrom:
          secretKeyRef:
            name: credentials-volume
            key: webhook-url