apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: csv-to-stdout-sample
spec:
  entrypoint: embulk
  arguments:
    artifacts:
    - name: embulk-config
      raw:
        data: |
          in:
            type: file
            path_prefix: 'data/'
            decoders:
            - {type: gzip}
            parser:
              charset: UTF-8
              newline: CRLF
              type: csv
              delimiter: ','
              quote: '"'
              escape: '"'
              null_string: 'NULL'
              skip_header_lines: 1
              columns:
              - {name: customer_id, type: string}
              - {name: customer_name, type: string}
              - {name: gender_cd, type: string}
              - {name: gender, type: string}
              - {name: birth_day, type: timestamp, format: '%Y-%m-%d'}
              - {name: age, type: long}
              - {name: postal_cd, type: string}
              - {name: address, type: string}
              - {name: application_store_cd, type: string}
              - {name: application_date, type: string}
              - {name: status_cd, type: string}
          filters:
            - type: column
              columns: 
                - {name: customer_id, type: string}
                - {name: gender_cd, type: string}
                - {name: gender, type: string}
                - {name: birth_day, type: timestamp, format: '%Y-%m-%d'}
                - {name: age, type: long}
                - {name: postal_cd, type: string}
                - {name: application_store_cd, type: string}
                - {name: application_date, type: string}
                - {name: status_cd, type: string}
          out: 
            type: stdout       
  workflowTemplateRef:
    name: embulk-template